import { APP_PREFIX_PATH } from 'constants/route.constant';
import {
  NAV_ITEM_TYPE_TITLE,
  NAV_ITEM_TYPE_COLLAPSE,
  NAV_ITEM_TYPE_ITEM,
} from 'constants/navigation.constant';
import { ADMIN, USER } from 'constants/roles.constant';

const lmsNavigationConfig = [
  {
    key: 'lms',
    path: '',
    title: 'LMS',
    // translateKey: 'nav.apps',
    icon: 'apps',
    type: NAV_ITEM_TYPE_TITLE,
    authority: [ADMIN, USER],
    subMenu: [
      {
        key: 'home',
        path: '',
        title: 'Home',
        // translateKey: 'nav.pages.welcome',
        icon: 'dataDisplay',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [ADMIN, USER],
        subMenu: [],
      },
      {
        key: 'apps.project',
        path: '',
        title: 'Products',
        // translateKey: 'nav.appsProject.project',
        icon: 'knowledgeBase',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [ADMIN, USER],
        subMenu: [
          {
            key: 'appsProject.dashboard',
            path: '',
            //  /app/lms/AdminUi/Courses/coursenavbar
            // ${APP_PREFIX_PATH}/project/dashboard
            title: 'Courses',
            //  translateKey: 'nav.appsProject.dashboard',
            icon: '',
            type: NAV_ITEM_TYPE_ITEM,
            authority: [ADMIN, USER],
            subMenu: [],
          },
          {
            key: 'appsProject.projectList',
            path: '',
            //`${APP_PREFIX_PATH}/project/project-list`
            title: 'Bundles',
            // translateKey: 'nav.appsProject.projectList',
            icon: '',
            type: NAV_ITEM_TYPE_ITEM,
            authority: [ADMIN, USER],
            subMenu: [],
          },
          {
            key: 'appsProject.scrumBoard',
            path: ``,
            // ${APP_PREFIX_PATH}/project/scrum-board
            title: 'Mock Tests',
            //  translateKey: 'nav.appsProject.scrumBoard',
            icon: '',
            type: NAV_ITEM_TYPE_ITEM,
            authority: [ADMIN, USER],
            subMenu: [],
          },
          {
            key: 'appsProject.issue',
            path: '',
            title: 'Test Series',
            // translateKey: 'nav.appsProject.issue',
            icon: '',
            type: NAV_ITEM_TYPE_ITEM,
            authority: [ADMIN, USER],
            subMenu: [],
          },
          {
            key: 'Caregories',
            path: '',
            title: 'Caregories',
            //  translateKey: 'nav.appsProject.issue',
            icon: '',
            type: NAV_ITEM_TYPE_ITEM,
            authority: [ADMIN, USER],
            subMenu: [],
          },
        ],
      },
      {
        key: 'apps.crm',
        path: '',
        title: 'User Management',
        // translateKey: 'nav.appsCrm.crm',
        icon: 'crm',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [ADMIN, USER],
        subMenu: [
          {
            key: 'appsCrm.dashboard',
            path: ``,
            // ${APP_PREFIX_PATH}/crm/dashboard
            title: 'Learner',
            // translateKey: 'nav.appsCrm.dashboard',
            icon: '',
            type: NAV_ITEM_TYPE_ITEM,
            authority: [ADMIN, USER],
            subMenu: [],
          },
          {
            key: 'appsCrm.calendar',
            path: ``,
            title: 'Admin',
            // translateKey: 'nav.appsCrm.calendar',
            icon: '',
            type: NAV_ITEM_TYPE_ITEM,
            authority: [ADMIN, USER],
            subMenu: [],
          },
          {
            key: 'appsCrm.customers',
            path: ``,
            title: 'Instructor',
            //  translateKey: 'nav.appsCrm.customers',
            icon: '',
            type: NAV_ITEM_TYPE_ITEM,
            authority: [ADMIN, USER],
            subMenu: [],
          },
          {
            key: 'appsCrm.customerDetails',
            path: ``,

            // ${APP_PREFIX_PATH}/crm/customer-details?id=8
            title: 'Affiliates',
            //  translateKey: 'nav.appsCrm.customerDetails',
            icon: '',
            type: NAV_ITEM_TYPE_ITEM,
            authority: [ADMIN, USER],
            subMenu: [],
          },
        ],
      },

      {
        key: 'asset library',
        path: '/',
        title: 'Asset Library',
        // translateKey: 'nav.pages.welcome',
        icon: 'crypto',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [ADMIN, USER],
        subMenu: [],
      },

      {
        key: 'reports',
        path: '/',
        title: 'Reports',
        // translateKey: 'nav.pages.welcome',
        icon: 'sales',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [ADMIN, USER],
        subMenu: [],
      },

      {
        key: 'manage',
        path: '/',
        title: 'Manage',
        // translateKey: 'nav.pages.welcome',
        icon: 'forms',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [ADMIN, USER],
        subMenu: [],
      },

      {
        key: 'settings',
        path: '/',
        title: 'Settings',
        // translateKey: 'nav.pages.welcome',
        icon: 'settings',
        type: NAV_ITEM_TYPE_ITEM,
        authority: [ADMIN, USER],
        subMenu: [],
      },

      {
        key: 'apps.account',
        path: '',
        title: 'Account',
        translateKey: 'nav.appsAccount.account',
        icon: 'account',
        type: NAV_ITEM_TYPE_COLLAPSE,
        authority: [ADMIN, USER],
        subMenu: [
          {
            key: 'appsAccount.settings',
            path: `${APP_PREFIX_PATH}/account/settings/profile`,
            title: 'Settings',
            translateKey: 'nav.appsAccount.settings',
            icon: '',
            type: NAV_ITEM_TYPE_ITEM,
            authority: [ADMIN, USER],
            subMenu: [],
          },
          {
            key: 'appsAccount.invoice',
            path: `${APP_PREFIX_PATH}/account/invoice/36223`,
            title: 'Invoice',
            translateKey: 'nav.appsAccount.invoice',
            icon: '',
            type: NAV_ITEM_TYPE_ITEM,
            authority: [ADMIN, USER],
            subMenu: [],
          },
          {
            key: 'appsAccount.activityLog',
            path: `${APP_PREFIX_PATH}/account/activity-log`,
            title: 'Activity Log',
            translateKey: 'nav.appsAccount.activityLog',
            icon: '',
            type: NAV_ITEM_TYPE_ITEM,
            authority: [ADMIN, USER],
            subMenu: [],
          },
          {
            key: 'appsAccount.kycForm',
            path: `${APP_PREFIX_PATH}/account/kyc-form`,
            title: 'KYC Form',
            translateKey: 'nav.appsAccount.kycForm',
            icon: '',
            type: NAV_ITEM_TYPE_ITEM,
            authority: [ADMIN, USER],
            subMenu: [],
          },
        ],
      },
    ],
  },
];

export default lmsNavigationConfig;
